name: Generate Build zip

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build distributable zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #v2.37.2
      with:
        php-version: '7.4'
        tools: composer

    - name: Install production dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build plugin zip
      uses: 10up/action-wordpress-plugin-build-zip@stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
