name: Generate POT file
on:
  pull_request:
    branches: [ trunk ]

jobs:
  WP_Generate_POT_File:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: WordPress .pot File Generator
      uses: iamdharmesh/action-wordpress-pot-generator@main
      with:
        destination_path: './languages'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
